-- AlterTable
ALTER TABLE "invoice_items" ALTER COLUMN "quantity" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "discount" DROP NOT NULL;

-- AlterTable
ALTER TABLE "invoices" ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "subTotal" DROP NOT NULL,
ALTER COLUMN "dueAt" DROP NOT NULL,
ALTER COLUMN "invoice_number" DROP NOT NULL,
ALTER COLUMN "issueAt" DROP NOT NULL,
ALTER COLUMN "totalDiscount" DROP NOT NULL,
ALTER COLUMN "totalPrice" DROP NOT NULL,
ALTER COLUMN "totalTax" DROP NOT NULL;
