-- AlterTable
ALTER TABLE "purchases" ADD COLUMN     "due" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "paid" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "subTotal" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "tax_id" TEXT,
ADD COLUMN     "total" DOUBLE PRECISION DEFAULT 0;
