export const ParentChildMap = {
  ASSET: ['CURRENT_ASSET', 'INVENTORY_ASSET', 'NON_CURRENT_ASSET'],
  LIABILITY: ['CURRENT_LIABILITIES', 'LONG_TERM_LIABILITIES'],
  EQUITY: ['SHARE_CAPITAL', 'RETAINED_EARNINGS', 'OWNERS_EQUITY'],
  INCOME: ['SALES_REVENUE', 'OTHER_REVENUE'],
  EXPENSE: [
    'COST_OF_GOODS_SOLD',
    'PAYROLL_EXPENSES',
    'GENERAL_AND_ADMIN_EXPENSES',
  ],
} as const;
